[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.120.4"
  HUGO_EXTENDED = "true"

[[redirects]]
  from = "/private"
  to = "/layout/?access=private-apartment-view"
  status = 302