baseURL = "https://example.org/"
languageCode = 'en-us'
title = 'Apartment Theme Demo'

[params]
  author = "Hugo Themes"
  description = "Example site built with Hugo and the Apartment theme."

[menu]
  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
  [[menu.main]]
    name = 'Gallery'
    pageRef = '/gallery'
    weight = 25
  [[menu.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 30

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
